External review
svitalis123/Book-an-Appointment pull request #19
Opened 2023-03-16 14:58 UTC by shuhad786

## Final Capstone 
In this pull request, we
- Followed the layout of [the provided design](https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign). 
- Changed only the titles, descriptions, and photos - in order to create a website about something other than motorcycles.
Selected a Car Repairs theme for our web app.

- Implemented core features for a team of size 4
  - The user is logged into the website, only by typing the username 
  - Added a navigation panel with the following links:
    - Car repairs theme
    - Reservation form.
    - Reservations page
    - Add reservations form
    - Delete reservations form
 - Created and displayed a list of services on the main page
- Implemented a details page with its full description.
- Made the app responsive, creating both mobile and desktop versions.
- Implemented a Delete item" link in the navigation panel that users can click on to see a list of all items with the title and delete button.
- username and selected item are autofilled on the service form
- Implemented the reserve page.
- Implemented My reservations link in the navigation panel where users can click on to see a list of their reservations (with information about item name, date and city).
- Added full documentation for the API.

2023-03-16 17:57 UTC, mcrd25 requested changes
Hi TEAM, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- Followed Rails best practices for msot part  ✔️ 
- Routes are well done ✔️ 
-  Meet basic usage requirements ✔️ 

## Required Changes ♻️
_Check the comments under the review._
- I don't see any documentation, Please add. You may use swagger or simple README documentation to show how to use API (endpoints etc)
- You are missing tests. When doing these tests consider both postive and negative scenarios
- Your README needs to look a bit more professional.
- I am missing reference to Front-End in Pr, when I do go to FR I don't see the PR from develop to main but rather feature branch to main. 
- Rememeber when building your Front-end to ensure that you  Don't forget that the application needs to look exactly like design with exception of photos, titles and descriptions
-  Ensure That you use resuable componenets for code that repeats itself often

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Consider adding tests to your front-end

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-16 17:57 UTC, mcrd25 commented on README.md
> +  <img class="README-logo" src="./app/assets/logo-jpg.jpg" alt="logo" width="140"  height="150" />
Your README is a bit confusing. Since it's the README for your back-end try to focus on rails implementation.

2023-03-16 17:57 UTC, mcrd25 commented on README.md
> +  <img class="README-logo" src="./app/assets/logo-jpg.jpg" alt="logo" width="140"  height="150" />
The README is a bit untidy as well, maybe try to get it looking a bit more professional

2023-03-16 17:57 UTC, mcrd25 commented on README.md
> +rails db:seed (preloaded information for easy access)
[OPTIONAL] Maybe you should add seeds yourself.

2023-03-16 17:57 UTC, mcrd25 commented on app/models/reservation.rb
> +  validates :service, presence: true
[OPTIONAL] is presence the only thing you can think of to validate in your models?

2023-03-17 07:58 UTC, Meltrust requested changes
Hi TEAM,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:


-  Nice code organization ✔️ 
-  Readme has been improved✔️ 




#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2023-03-17 07:58 UTC, Meltrust commented on README.md
> +  <img class="README-logo" src="./app/assets/logo-jpg.jpg" alt="logo" width="140"  height="150" />
- [ ] As the previous reviewer pointed out, your app is missing unit tests.  Kindly add some so your app's integrity is assured.  

## Explanation

In job interviews, and in the industry itself, you will be _required_ to write tests.  If a potential employer comes to test your app, he/she will be _expecting_ to see unit tests.

If you get used to implementing tests, nothing will stop you.  💪

2023-03-17 07:58 UTC, Meltrust commented on README.md
> +  <img class="README-logo" src="./app/assets/logo-jpg.jpg" alt="logo" width="140"  height="150" />
- [ ] As the previous reviewer pointed out, you are missing the API docs.  Since you are a group of 4, this is a project requirement.

Suggestion:  Use the rswag gem.  It's simple, very functional, and the whole industry is using it.  👍

2023-03-17 07:58 UTC, Meltrust commented on README.md
>  This project is [MIT](./LICENSE) licensed.
- [ ] OPTIONAL: On the "License" section of your readme, the link is broken because it points to a file that does not exist in your project.

## Tips and extra help

Go [here](https://github.com/microverseinc/readme-template), grab the `MIT.md` file from that repo, paste it on the root of your project, and link to it in the "License" section of your readme.

That way, your app will be well documented 💪

2023-03-17 15:59 UTC, Meltrust approved these changes
#### Hi team,


# **Wow, you did it 🎉**
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for the changes implemented 💪 🥇 ㊗️ 
#### _Unless you want to add more features, go ahead to your final presentation ⏩ ⏩ ⏩_ 
## You are about to finish the Microverse program.  You have come a long way!!!




### Good luck in the software industry!!  I'll see you there. ✨
### **Congratulations!!!!!!**  🎉
![applause](https://media.giphy.com/media/srg19CG0cKMuI/giphy.gif)

### To highlight

- Readme has been corrected✔️ 
- Tests have been added✔️ 




Cheers and Happy coding!👏👏👏


------

2023-03-17 16:39 UTC, merged

2023-03-17 17:08 UTC, Nemwel-Boniface reviewed
## Hello team  👋,

I am Nemwel your reviewer.


## _This is an additional review as a result of the second opinion request._

Kindly note that the reviews you request for the **Final group capstone** project are usually "OPTIONAL" and they serve as a second opinion on what you might have missed and implement to make it better for the presentation of the project. This basically means that you have the liberty to choose whether you want to make the changes or not.


However, since I can see that you made the changes and it was approved kudos guys! :clap: :clap: 

In case anything is not 100% clear tag me @Nemwel-Boniface so that I get the notification.

Keep rocking 🚀!